import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from './components/Navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Next.JS Starter Template',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col min-h-screen bg-background">
          <Navbar />
          <div className="flex flex-grow">
            <main className="max-w-4xl mx-auto p-4 flex-grow">{children}</main>
          </div>
          <footer className="bg-primary text-secondary-foreground p-4 text-center">
            <p>&copy; Next.js Starter Template</p>
          </footer>
        </div>
      </body>
    </html>
  );
}
